name: Template Issue
description: Report an issue or bug with an existing template such as errors, outdated variables, etc.
title: "[Template Issue]: "
labels: ["template-bug"]
assignees:
  - ImSkully
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to submit a report, please take a few minutes to fill out the details below to provide more information about your issue.
  - type: dropdown
    id: template-name
    attributes:
      label: Application Template
      description: What is the name of the application template you are reporting?
      options:
        - OpenProject
        - Vikunja
        - Zipline
        - Other
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: What is the bug or issue with the template you are reporting?
      description: Please provide a clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    id: unraid-version
    attributes:
      label: Unraid Version
      description: What version of Unraid did you encounter this issue on?
      placeholder: e.g. 7.0.0 or leave blank if not applicable
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Include any other useful information here.
  - type: textarea
    id: additional-logs
    attributes:
      label: Additional Logs
      description: Include any helpful logs related to your issue.
      render: shell
  - type: checkboxes
    id: agreement
    attributes:
      label: Confirmation
      description: Have you checked to ensure your issue is not a duplicate of an [existing one](https://github.com/ImSkully/unraid-templates/issues)?
      options:
        - label: Yes, my issue has not already been reported.
          required: true